version: '3.9'
services:
  nginx:
    image: guvensen/nginx-1.2-alphine:1.0
    container_name: nginx
    ports:
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      - target: 80
        published: 80
        mode: host
        protocol: tcp
    volumes:
      - nginx-config:/etc/nginx/conf.d/
      - nginx-www:/var/www/
      - php8-www:/var/www-php8/
      - nginx-log:/var/log/nginx/
      - certbot-certs:/etc/letsencrypt/certs/
      - /etc/localtime:/etc/localtime:ro # Sync container and host machine datetime.
    networks:
      - backend
volumes:
  nginx-config:
    external: true
  php8-www:
    external: true
  nginx-www:
    external: true
  nginx-log:
    external: true
  certbot-certs:
    external: true
networks:
  backend:
    external: true
